apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-app
    spec:
      containers:
      - image: 220937581726.dkr.ecr.us-east-1.amazonaws.com/todo-app:1.0
        name: express
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            protocol: TCP
      imagePullSecrets:
      - name: aws-ecr

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: todo-app
  type: LoadBalancer
